### PR TITLE
Upgrade to laravel 11

### PR DESCRIPTION
**Pull request by philippejadin**
That was a bumpy road because some packages changed completely. 
Looking at you intervention/image 2 -> 3

### CODE REVIEW

**Comment by linc** [comment]
This is a very challenging change to review because it's incredibly large. You've mixed the Laravel upgrade itself with several issue fixes in one large change set.

In the future, it would be helpful to identify the issues from the upgrade and tackle those as separate issue tickets + PRs sequentially, then doing the Laravel upgrade when those are all reviewed & merged. That helps isolate fixes so they can be tested independently.

It's quite an overwhelming task to look at 4,000+ lines of changed code and provide feedback when I'm not familiar with the problems you found along the way.

**Comment by linc** [comment]
I also see quite a few "code formatting" changes in here, which is muddying the water even more. That's another type of change it's best to isolate — formatting changes that shouldn't change functionality at all.

I'm not sure I'll be able to provide much useful feedback given the size of the change vs my familiarity with the code being changed currently.

**Comment by philippejadin** [comment]
You are absolutely right on both fronts. I started the upgrade and came to a chicken and egg problem where lot of interdependent stuff happened. Since I really dislike the chore of upgrading (quite a lot of work for nearly no new features), I thought, screw it, let's merge it all at once, at least it's all behind us. 

I will document here what I've done in order to see if I made the correct decision. 

Sorry for the lack of team spirit on this one, probably inherited from my previous years working mostly alone.

Also I will try in the future to upgrade to latest laravel when it is needed instead of jumping 3 versions at once 🥵.

More in the following days.

**Comment by linc** [comment]
No worries, sounds good. Just explaining why I’m not going to be very useful for this review. 😅 I did pull it locally and didn’t immediately find any glaring issues.

**Pull request merged**
