### PR TITLE
Stop date/time needs not to be set.

### PR DESCRIPTION
**Pull request by zerline**
By default, `stop_date` will be equal to `start_date`, and then *not displayed*.

### CODE REVIEW

**Comment by linc** [comment]
I like this simplification. Are you confident there are no other ripple effects from this change? This is a user-facing change so things like UI instructions being out of sync would be something to consider, or whether the 1-hour default is assumed anywhere else.

**Review by philippejadin — COMMENTED** [review]
I'm ok with the change if both of you think it's a better way to see it. I'm just worried about what happens in the calendar js view. Did you try it ?

**Comment by philippejadin** [comment]
I just checked, events without stop time are shown fine in js calendar, but unfortunately, the drag and drop event creation on js calendar does not store end event. There is something wrong in the if logic, it should handle the case where no end date is defined, but an end time is defined (I think). The logic should be simple and rock solid, if you find a way to do that, it would be great :)

**Comment by zerline** [comment]
Sorry, I don't understand. I certainly have not tried all possible cases but still.  I may be searching in the wrong place. Can you help with a screenshot, for example?

**Comment by philippejadin** [comment]
Sorry, I'll try to explain better. If you go to a group's calendar, select the grid view (calendar js), in the calendar grid (week view for example), click and drag on several hours, to create an event for example from 6:30 to 8:00 : 
Capture d’écran du 2024-12-28 22-33-42

Then you will see an event creation form like this one : 
Capture d’écran du 2024-12-28 22-33-52

But when you click on create, the event has incorrect end time saved (or more probably no end time encoded at all, js calendar defaulting to one hour) : 
Capture d’écran du 2024-12-28 22-34-17

**Comment by zerline** [comment]
Thank you. I just requested #521.

**Pull request closed without merging**
