### PR TITLE
#390 Add user undelete feature.

### PR DESCRIPTION
**Pull request by 66iii**
Allow admins to undelete users from the users admin list.

Teamwork with contributors @seb-mathieu , @philippeou, @VH-NG and @M134DRAVENN ( @slamgoat ).

### CODE REVIEW

**Comment by philippejadin** [comment]
Hello, Thank you for the PR. I'm ready to merge it as is, but if you still have time to work on it, it would be nice to use laravel model binding instead of using $id in the controller. It doesn't work out of the box with trashed models, but there is a workaround, see here : https://laravel.com/docs/8.x/routing#implicit-soft-deleted-models

If you don't have time for a second PR, let me know, I will merge this one, and anyone will be able to work from there.

Thank you for the time taken working on this !

**Comment by philippejadin** [comment]
Any news on this PR? If you don't have time to work more on it, let me know, I will merge it as is :-)

**Comment by 66iii** [comment]
I dont have time for the moment

**Comment by philippejadin** [comment]
I merge it as is, so we can move on. Thank you everyone involved in this PR !

**Pull request merged**
